apiVersion: v2
name: calcom-stack
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "v3.3.1"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.23
  - name: calcom
    repository: https://pyrrha.github.io/calcom-helm
    version: 0.1.5
